### PR TITLE
Add ignore array order for proxy

### PR DESCRIPTION
**Pull request by hex-y**
*Description of changes:*
Adding "insertionOrder": false to proxy properties, so cloudformation can ignore order when comparing. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by noshaws — APPROVED** [review]
Approved

**Comment by hex-y** [comment]
Added the change for target-group

**Review by zhuyibo-amzn — APPROVED** [review]

**Review by noshaws — CHANGES_REQUESTED** [review]
How about target group changes?

**Comment by hex-y** [comment]
target group changes included!

**Comment by noshaws** [comment]
Great!

**Pull request merged**
